name: tests

on:
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest --cov-report=term --cov-report=html:coverage/htmlcov --cov-report=xml:coverage/coverage.xml --cov-report=markdown:coverage/coverage.md

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-${{ matrix.python-version }}
          path: coverage

      - name: Publish code coverage badge
        run: |
          total=`tail -n 1 coverage/coverage.md | grep -oE "[0-9]+%" | tr -d '%'`

          if   (( total >= 90 )); then
              color=brightgreen
          elif (( total >= 80 )); then
              color=green
          elif (( total >= 70 )); then
              color=yellowgreen
          elif (( total >= 60 )); then
              color=yellow
          elif (( total >= 50 )); then
              color=orange
          else
              color=red
          fi

          curl "https://img.shields.io/badge/coverage-$total%25-$color" > badge.svg

      - name: Archive code coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge-${{ matrix.python-version }}.svg
          path: badge.svg
